export { default as LandingPage } from "./LandingPage";
export { default as LoginPage } from "./LoginPage";
export { default as NotFoundPage } from "./NotFoundPage";
export { default as RegisterPage } from "./RegisterPage";
export { default as SearchFriendsPage } from "./SearchFriendsPage";
export { default as SearchResultsPage } from "./SearchResults";
export { default as FriendsPage } from "./FriendsPage";
export { default as HomePage } from "./HomePage";
export { default as MyEventsPage } from "./MyEventsPage";
